Update suggested permissions for .shortcuts/icons/
termux/termux-widget pull request #69
Opened 2021-12-12 01:57 UTC by SuspectTyrannosaurus

Change the `chmod` command suggested for the `~/. shortcuts/icons/` directory from `600` to `700`. Without `u+x`, users are not able to `cp` files into the directory.

2021-12-12 02:08 UTC, SuspectTyrannosaurus commented
I created Issue #68 to document this PR. (I can't find the button to link the PR to the Issue, so I am just mentioning it in a comment.)

2021-12-12 04:49 UTC, agnostic-apollo requested changes
Thanks for noticing the mistake for the wrong directory permission but change the command to `chmod -R a-x,u=rwX,go-rwx /data/data/com.termux/files/home/.shortcuts/icons`. It was originally done so that icon files didn't have execute permissions.  This will result in directories having `700` and files having `600`.

https://stackoverflow.com/a/17091831/14686958

2021-12-13 00:15 UTC, SuspectTyrannosaurus commented
@agnostic-apollo 

This is a sample command in a walkthrough creating the directory with no contents, so the proposed change to the chmod would (in theory) have no effect, since it only affects the directory and its _current_ contents.

The example command is, however, written in a way such that it won't cause an error if the directory exists (`mkdir -p`), and the recursive flag on chmod would indeed affect any existing files in that case.

Perhaps the tutorial's sample commands should be rewritten to not be so graceful, so as to prevent making any existing files executable?

To be really safe, I think the app itself would need to be modified to scan for permissions and refuse to proceed if unsafe executable flags are set.

2021-12-14 02:28 UTC, SuspectTyrannosaurus reviewed
I made the change recommended. In the odd case where someone has already created and populated the directory before running the command to create it, the pre-existing files should be set with the most appropriate permissions.

2021-12-17 09:25 UTC, agnostic-apollo approved these changes

2021-12-17 09:25 UTC, agnostic-apollo commented
Sorry, forgot about this. Merging. Thanks again!

2021-12-17 09:25 UTC, merged